language: node_js
install:
  - gcc -v
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  - gcc -v
  - npm install --build-from-source
node_js:
  - "14"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - gcc-9
      - g++-9
env:
  - CXX=g++-9 && CC=gcc-9
sudo: false
distro: focal
